@url = http://localhost:5269/api

### POST create budget
POST {{url}}/budgets
Content-Type: application/json

{
  "name": "Default Budget",
  "description": "This is a default budget description."
}

###
@id = 9d505868-48f0-4419-92fe-0fe3a39166f2

### PUT update budget details
PUT {{url}}/budgets/{{id}}
Content-Type: application/json

{
  "id": "{{id}}",
  "name": "Updated Budget Name",
  "description": "Updated description for the budget."
}

### DELETE budget
DELETE {{url}}/budgets/{{id}}
Content-Type: application/json

### GET budget
GET {{url}}/budgets/f7246720-18b5-4e14-a365-f52761d1e146

### GET all budgets
GET {{url}}/budgets

